# fly.toml app configuration file generated for muni-chenchen on 2023-07-04T19:22:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muni-chenchen"
primary_region = "bog"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
